# Generated by Django 5.0.2 on 2024-02-17 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauka', '0002_alter_user_repetiion_types_alter_user_words_to_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('learn_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_date', models.DateField()),
                ('result', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nauka.word')),
            ],
        ),
    ]
