# Generated by Django 5.0.2 on 2024-02-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauka', '0004_rename_repetiion_types_user_repetition_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('learning_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('learning_date', models.DateField()),
                ('result', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nauka.word')),
            ],
        ),
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
