# Generated by Django 5.0.2 on 2024-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nauka', '0005_learning_delete_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(null=True),
        ),
    ]
